set -euo pipefail

echo "Generating code for javascript"

# Working directory is the directory in which this script is located!
cd "$(dirname "$0")"

# Remove everything except manually written files
echo "  Cleaning up old files..."
rm -rf keelson/payloads
rm -rf keelson/interfaces
rm -rf keelson/google
rm -rf keelson/Envelope.ts
rm -rf keelson/subjects.json
rm -rf keelson/qos.json
rm -rf keelson/interfaces.json

echo "  Creating directories"
mkdir -p keelson/payloads
# mkdir -p ../../messages/payloads/js

echo "      Converting subjects.yaml to json"
npx js-yaml ../../messages/subjects.yaml >> keelson/subjects.json

echo "      Converting qos.yaml to json"
npx js-yaml ../../messages/qos.yaml >> keelson/qos.json

echo "      Converting interfaces.yaml to json"
npx js-yaml ../../messages/interfaces.yaml >> keelson/interfaces.json


echo "  Generating code for Envelope.proto..."
uv run protoc \
    --plugin=./node_modules/.bin/protoc-gen-ts_proto \
    --ts_proto_out=keelson \
    --proto_path ../../messages \
    ../../messages/Envelope.proto

echo "  Generating payloads"
uv run protoc \
    --plugin=./node_modules/.bin/protoc-gen-ts_proto \
    --ts_proto_out=keelson/payloads \
    --proto_path=../../messages/payloads \
    --ts_proto_opt=esModuleInterop=true \
    --ts_proto_opt=outputIndex=true \
    --ts_proto_opt=outputTypeRegistry=true \
    ../../messages/payloads/*.proto \
    ../../messages/payloads/**/*.proto

# Creating a directory for the interface if it doesnt already exists
echo "	Creating directory for interfaces..."
mkdir -p keelson/interfaces

# Generate code for interfaces. Interfaces may import shared domain types
# (Coordinate, Mission, ...) from the keelson domain-type pool; those
# imported payload protos are compiled into keelson/interfaces/ as well so
# ts-proto's relative imports resolve (unlike Python, ts-proto has no
# global descriptor pool, so the duplicate compilation is harmless).
echo "	Generating code for interfaces..."
# Collect the transitive closure of domain protos the interfaces pull in:
# an imported payload proto may itself import further payload protos
# (Mission.proto -> Coordinate.proto), and every file in the closure must
# be compiled into keelson/interfaces/ for ts-proto's relative imports to
# resolve.
DOMAIN_FILES=""
PENDING="$(grep -hoE '^import "[A-Za-z0-9_]+\.proto"' ../../interfaces/*.proto | sed -E 's/^import "(.*)"$/\1/' | sort -u)"
while [ -n "${PENDING}" ]; do
    NEXT=""
    for imported in ${PENDING}; do
        case " ${DOMAIN_FILES} " in *" ${imported} "*) continue;; esac
        if [ -f "../../messages/payloads/${imported}" ]; then
            DOMAIN_FILES="${DOMAIN_FILES} ${imported}"
            NEXT="${NEXT} $(grep -hoE '^import "[A-Za-z0-9_]+\.proto"' "../../messages/payloads/${imported}" | sed -E 's/^import "(.*)"$/\1/')"
        fi
    done
    PENDING="$(echo ${NEXT} | tr ' ' '\n' | sort -u)"
done
DOMAIN_PROTOS=""
for f in ${DOMAIN_FILES}; do
    DOMAIN_PROTOS="${DOMAIN_PROTOS} ../../messages/payloads/${f}"
done
uv run protoc \
    --plugin=./node_modules/.bin/protoc-gen-ts_proto \
    --ts_proto_out=keelson/interfaces \
    --proto_path=../../interfaces \
    --proto_path=../../messages/payloads \
    --ts_proto_opt=esModuleInterop=true \
    --ts_proto_opt=outputServices=generic-definitions \
    ../../interfaces/*.proto ${DOMAIN_PROTOS}

# Emit the service registry: interfaces.yaml key -> generated ts-proto
# ServiceDefinition, so generic clients can enumerate interfaces and
# resolve procedure request/response codecs at runtime (the JS
# equivalent of the Python SDK's keelson.interfaces introspection).
echo "	Generating interface service registry..."
REGISTRY=keelson/interfaces/serviceRegistry.ts
echo "// Generated by generate_javascript.sh - DO NOT EDIT." > ${REGISTRY}
grep -E '^[a-z_]+/v[0-9]+:' ../../messages/interfaces.yaml | while read -r line; do
    key="${line%%:*}"
    service_full="$(echo "${line#*:}" | tr -d ' ')"
    service="${service_full##*.}"
    echo "import { ${service}Definition } from \"./${service}\";" >> ${REGISTRY}
done
echo "" >> ${REGISTRY}
echo "export const serviceDefinitions = {" >> ${REGISTRY}
grep -E '^[a-z_]+/v[0-9]+:' ../../messages/interfaces.yaml | while read -r line; do
    key="${line%%:*}"
    service_full="$(echo "${line#*:}" | tr -d ' ')"
    service="${service_full##*.}"
    echo "  \"${key}\": ${service}Definition," >> ${REGISTRY}
done
echo "} as const;" >> ${REGISTRY}

echo "Javascript done!"