# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NetworkPingPong.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'NetworkPingPong.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15NetworkPingPong.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n\x0bNetworkPing\x12+\n\x07sent_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"\x8c\x01\n\x0bNetworkPong\x12+\n\x07sent_at\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1a\n\x04ping\x18\x02 \x01(\x0b\x32\x0c.NetworkPing\x12\x34\n\x10ping_received_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2=\n\x0fNetworkPingPong\x12*\n\x0cping_network\x12\x0c.NetworkPing\x1a\x0c.NetworkPongb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NetworkPingPong_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKPING']._serialized_start=58
  _globals['_NETWORKPING']._serialized_end=133
  _globals['_NETWORKPONG']._serialized_start=136
  _globals['_NETWORKPONG']._serialized_end=276
  _globals['_NETWORKPINGPONG']._serialized_start=278
  _globals['_NETWORKPINGPONG']._serialized_end=339
# @@protoc_insertion_point(module_scope)
