# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Subscriber.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'Subscriber.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Subscriber.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0eResponse.proto\"\x7f\n\rSubscriptions\x12\x38\n\rsubscriptions\x18\x01 \x03(\x0b\x32!.Subscriptions.SubscriptionsEntry\x1a\x34\n\x12SubscriptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x80\x01\n\nSubscriber\x12;\n\x11get_subscriptions\x12\x16.google.protobuf.Empty\x1a\x0e.Subscriptions\x12\x35\n\x11set_subscriptions\x12\x0e.Subscriptions\x1a\x10.SuccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Subscriber_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIPTIONS_SUBSCRIPTIONSENTRY']._loaded_options = None
  _globals['_SUBSCRIPTIONS_SUBSCRIPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_SUBSCRIPTIONS']._serialized_start=65
  _globals['_SUBSCRIPTIONS']._serialized_end=192
  _globals['_SUBSCRIPTIONS_SUBSCRIPTIONSENTRY']._serialized_start=140
  _globals['_SUBSCRIPTIONS_SUBSCRIPTIONSENTRY']._serialized_end=192
  _globals['_SUBSCRIBER']._serialized_start=195
  _globals['_SUBSCRIBER']._serialized_end=323
# @@protoc_insertion_point(module_scope)
