# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WHEPProxy.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'WHEPProxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fWHEPProxy.proto\"(\n\x0bWHEPRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0b\n\x03sdp\x18\x02 \x01(\t\"\x1b\n\x0cWHEPResponse\x12\x0b\n\x03sdp\x18\x01 \x01(\t27\n\tWHEPProxy\x12*\n\x0bwhep_signal\x12\x0c.WHEPRequest\x1a\r.WHEPResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WHEPProxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WHEPREQUEST']._serialized_start=19
  _globals['_WHEPREQUEST']._serialized_end=59
  _globals['_WHEPRESPONSE']._serialized_start=61
  _globals['_WHEPRESPONSE']._serialized_end=88
  _globals['_WHEPPROXY']._serialized_start=90
  _globals['_WHEPPROXY']._serialized_end=145
# @@protoc_insertion_point(module_scope)
